import os
import requests
import base64
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

CLIENT_ID = os.getenv("EBAY_CLIENT_ID")
CLIENT_SECRET = os.getenv("EBAY_CLIENT_SECRET")

def get_ebay_access_token():
    """Exchanges Client Credentials for an eBay OAuth2 Application Access Token."""
    url = "https://api.ebay.com/identity/v1/oauth2/token"
    
    credentials = f"{CLIENT_ID}:{CLIENT_SECRET}"
    encoded_credentials = base64.b64encode(credentials.encode()).decode()
    
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "Authorization": f"Basic {encoded_credentials}"
    }
    
    data = {
        "grant_type": "client_credentials",
        "scope": "https://api.ebay.com/oauth/api_scope"
    }
    
    try:
        response = requests.post(url, headers=headers, data=data, timeout=5)
        if response.status_code == 200:
            return response.json().get("access_token")
        else:
            print(f"[eBay Auth Error] Status {response.status_code}: {response.text}")
            return None
    except Exception as e:
        print(f"[eBay Auth Exception]: {e}")
        return None


def fetch_price_by_query(query_string):
    """
    Queries eBay Motors using a full, pre-optimized search string generated by the Vision LLM.
    """
    token = get_ebay_access_token()
    if not token:
        return None
        
    url = "https://api.ebay.com/buy/browse/v1/item_summary/search"
    headers = {
        "Authorization": f"Bearer {token}",
        "X-EBAY-C-MARKETPLACE-ID": "EBAY_US"
    }
    
    params = {
        "q": query_string,
        "category_ids": "6030",  # Auto Parts & Accessories
        "limit": "5",
        "filter": "conditions:{USED|REFURBISHED}"
    }
    
    try:
        response = requests.get(url, headers=headers, params=params, timeout=5)
        if response.status_code == 200:
            data = response.json()
            items = data.get("itemSummaries", [])
            
            if not items:
                return None
                
            prices = [float(item["price"]["value"]) for item in items if "price" in item]
            return sum(prices) / len(prices) if prices else None
            
        return None
    except Exception as e:
        print(f"[eBay Search Exception]: {e}")
        return None


def fetch_part_market_price(make, year, part_name, model=None):
    """
    Queries eBay Motors using Year, Make, and Part Name.
    """
    if model:
        query = f"{year} {make} {model} {part_name}"
    else:
        query = f"{year} {make} {part_name}"
        
    return fetch_price_by_query(query)